const express=require('express');
const router=express.Router();
const logged=require('./modules/isLoggedIn.js');
const chatInterface=require('./modules/chat-interface.js');
const chatBetweenUsers=require('./modules/chat-between-users.js');
const getMessagesFromChat=require('./modules/get-messages-from-chat.js');
router.get('/', logged.isLoggedIn, chatInterface);
router.get('/chat', logged.isLoggedIn, chatBetweenUsers);
router.get('/chat/messages', getMessagesFromChat);
module.exports=router;